コマンド実行中にエラーが発生しました: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:727:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:831:23)
    at async _REST.request (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:1272:22)
    at async ChatInputCommandInteraction.reply (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:115:5)
    at async Object.execute (C:\Users\○○○○\Desktop\mycode\DiscordBot\commands\suggestFeature.js:15:9)
    at async Object.execute (C:\Users\○○○○\Desktop\mycode\DiscordBot\events\interaction.js:17:17) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1312591629210615868/aW50ZXJhY3Rpb246MTMxMjU5MTYyOTIxMDYxNTg2ODo4N01MQ1QzamRRQXRQU2poeDBTSm5XYTlXbHdVazFSTmEya1ZLOW1Fa3paOU5DMmt3ZWxoUGdMZ05RWGNrR3UwaFBmbXg1ajNkS1E4bkJSdVlSNmtISVdPbEtwWXR6QTNMbzhaUzdQZ3kyN2VGMXVpdklHRzg3QkhQa0J4QldjNg/callback'
}
node:events:497
      throw er; // Unhandled 'error' event
      ^

DiscordAPIError[40060]: Interaction has already been acknowledged.
    at handleErrors (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:727:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:831:23)
    at async _REST.request (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\@discordjs\rest\dist\index.js:1272:22)
    at async ChatInputCommandInteraction.reply (C:\Users\○○○○\Desktop\mycode\DiscordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:115:5)
    at async Object.execute (C:\Users\○○○○\Desktop\mycode\DiscordBot\events\interaction.js:20:17)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:402:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: 'エラーが発生しました。',
        tts: false,
        nonce: undefined,
        enforce_nonce: false,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined,
        applied_tags: undefined,
        poll: undefined
      }
    }
  },
  rawError: {
    message: 'Interaction has already been acknowledged.',
    code: 40060
  },
  code: 40060,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1312591629210615868/aW50ZXJhY3Rpb246MTMxMjU5MTYyOTIxMDYxNTg2ODo4N01MQ1QzamRRQXRQU2poeDBTSm5XYTlXbHdVazFSTmEya1ZLOW1Fa3paOU5DMmt3ZWxoUGdMZ05RWGNrR3UwaFBmbXg1ajNkS1E4bkJSdVlSNmtISVdPbEtwWXR6QTNMbzhaUzdQZ3kyN2VGMXVpdklHRzg3QkhQa0J4QldjNg/callback'
}

Node.js v20.17.0
